DROP TABLE IF EXISTS order_details CASCADE;
CREATE TABLE order_details (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
  sub_total INTEGER NOT NULL,
  tax_rate INTEGER NOT NULL,
  total_price INTEGER NOT NULL
);
